name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "202400,new,updated,small changes"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['202400','new','updated', 'small changes']"
        BANNED_LABELS: "do not merge"
        BANNED_LABELS_DESCRIPTION: "You are not allowed to merge PRs with the DO NOT MERGE label"