name: Weekly Link Check

on:
  schedule:
    # Run every Monday at 9:00 UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual trigger

jobs:
  jekyll_build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build --config=_config.yml,_config_production.yml -t

      - name: Pack artifacts
        run: tar -czf result.tar.gz _site

      - uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: result.tar.gz
          retention-days: 1 # Only keep for 1 day since this is a weekly check

  link_check_about:
    name: Check Links - About
    needs: jekyll_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unpack artifacts
        run: tar -xzf result.tar.gz

      - name: Check internal links (About)
        run: bundle exec rake check_about

  link_check_ca:
    name: Check Links - Cloud Administration
    needs: jekyll_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unpack artifacts
        run: tar -xzf result.tar.gz

      - name: Check internal links (CA)
        run: bundle exec rake check_ca

  link_check_pbc:
    name: Check Links - PBC
    needs: jekyll_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unpack artifacts
        run: tar -xzf result.tar.gz

      - name: Check internal links (PBC)
        run: bundle exec rake check_pbc

  link_check_dg:
    name: Check Links - Developer Guide
    needs: jekyll_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unpack artifacts
        run: tar -xzf result.tar.gz

      - name: Check internal links (DG)
        run: bundle exec rake check_dg

  link_check_integrations:
    name: Check Links - Integrations
    needs: jekyll_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unpack artifacts
        run: tar -xzf result.tar.gz

      - name: Check internal links (Integrations)
        run: bundle exec rake check_integrations
